### ISSUE TITLE
UDP socket

### ISSUE THREAD

**Issue by andreamatt** [yingshaoxo/fuckwsl2#1]
Thanks for tool.
Does it work with UDP ports too?

**Comment by yingshaoxo** [comment]
I made a simple change to the code

now it should be able to forward udp ports too. (but for now I don't have a win10 machine, can't compile it for you for now

**Comment by andreamatt** [comment]
netsh portproxy doesn't support udp, not sure how this could work. Even though it has the protocol parameter, only the "protocol=tcp" option is available atm. Check [here](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy#add-v4tov4)

**Comment by yingshaoxo** [comment]
OK, then I guess you should probably use Linux as your main OS. (win10 sucks

Trust me, PopOS is better than Win10.

**Comment by andreamatt** [comment]
Well, no. I found another solution anyway: [SSF](https://securesocketfunneling.github.io/ssf/#home)

**Comment by yingshaoxo** [comment]
Glad for you, and thanks for the sharing
